### ISSUE TITLE
Severe lack of null safety detected in Filestores!

### ISSUE THREAD

**Issue by nvnikolov** [datagraft/datagraft-portal#101]
The two metadata items for files - 'upload_format' and 'upload_filename' are referenced throughout the code without any checks if the values are empty. Empty values cause the attachment link to be corrupted. 

Thus far this has only caused one bug, but should be fixed to avoid further ones in the future.

**Comment by sdalgard** [comment]
Added default values to 'upload_format' and 'upload_filename'
