### ISSUE TITLE
Define ontology for new names in queries/show.json

### ISSUE THREAD

**Issue by sdalgard** [datagraft/datagraft-portal#107]
json.id @thing.slug 
json.set! 'foaf:publisher', @thing.user.username 
json.set! 'dcat:public', @thing.public 
json.set! 'dct:title', @thing.name 
json.set! 'dct:description', @thing.description 
json.set! 'dct:issued', @thing.created_at 
json.set! 'dct:modified', @thing.updated_at 
 
json.set! 'dcat:keyword', @thing.keywords 
json.set! '**query_text**', @thing.query 
json.set! '**query_type**', @thing.query_type 
json.set! '**sparql_endpoints**', @thing.sparql_endpoints, :id

**Comment by nvnikolov** [comment]
Have a read at https://www.w3.org/TR/vocab-dcat/ and see if you can find some concepts to map to
