### ISSUE TITLE
Show SPARQL endpoint page 

### ISSUE THREAD

**Issue by nvnikolov** [datagraft/datagraft-portal#14]
Endpoint info (tab)
- [x] Title, last modified, public/private, author, description, keywords
- [x] License (icon + description/license text)
- [x] SPARQL endpoint metadata (provisioned on, size)

Querying (tab)
- [x] SPARQL endpoint address (copy link)
- [x] Queries cards (search, filter by owned/public, run query against current endpoint, type of query - select/ask/construct..., card details)
- [x] Highlight associated queries
- [x] New query (button) - open and close, query input box, save as new query, execute
- [x] Query result (table display, pagination, search, download formats)
- [ ] Creating a file page/SPARQL endpoint page out of the results

**Comment by elvesater** [comment]
Created two new enhancement issues for milestone 0.2.0 and closed this.
