### ISSUE TITLE
Implement Quotas user interface

### ISSUE THREAD

**Issue by nvnikolov** [datagraft/datagraft-portal#25]
Replace dummy data with actual quota enforcement (UI only)

**Comment by nvnikolov** [comment]
It should include:
- number of SPARQL endpoints (10)
- number of triples total for all SPARQL endpoints (10Mil)
- volume of files (1 GB max)
- max number of (100 files)
- max number of transformations (100)

**Comment by sdalgard** [comment]
Implemented in branch "feature/quota"
