### ISSUE TITLE
Create main footer

### ISSUE THREAD

**Issue by nvnikolov** [datagraft/datagraft-portal#26]
- [x] Footer will contain API, Documentation, Privacy policy, etc.
- [x] Create Terms of Use page
- [x] Create Privacy Policy page
- [x] Create FAQ page
- [x] Create Cookie Policy page

**Comment by elvesater** [comment]
Updated the main footer with new and/or revised sections for FAQ, Privacy Policy, Terms of Use, Cookie Policy and Feedback. Pushed the changes to the sparql_endpoints branch.
