### ISSUE TITLE
Improve login and sign up pages

### ISSUE THREAD

**Issue by nvnikolov** [datagraft/datagraft-portal#30]
- [x] Links to the Privacy Policy, and Terms of Service (also to be deployed on DataGraft) 
- [x] Redo layout

**Comment by nvnikolov** [comment]
Have a look at https://github.com/dapaas/dapaas.github.io

**Comment by sdalgard** [comment]
Last changes included in branch "feature/Landingpage"

**Comment by sdalgard** [comment]
Ready for integration

**Comment by sdalgard** [comment]
Integrated
