### ISSUE TITLE
Adjust FAQ and Cookie Policy pages' content

### ISSUE THREAD

**Issue by taritaAna** [datagraft/datagraft-portal#36]
Please adjust the content to current requirements:
- [ ] Adjust Cookie Policy page content
- For the FAQ page supply the content for the following sections:
- [ ] Who developed DataGraft?
- [ ] Who funded DataGraft?
- [ ] Who maintains and operates DataGraft?
- [ ] What is a datapage?
- [ ] What features are planned for future releases? (I am not sure which ones are still actual)

Old FAQ page (https://datagraft.net/faq/) can be used as reference.

**Comment by elvesater** [comment]
Fixed this in January 2017.
