### ISSUE TITLE
Keywords panel in SPARQL endpoint pages does not display properly when no keywords specified

### ISSUE THREAD

**Issue by nvnikolov** [datagraft/datagraft-portal#42]
If there are no keywords, we should either hide the panel altogether, or show an empty one that is wider

Currently it displays as follows:
![image](https://cloud.githubusercontent.com/assets/8124245/20054456/59e0c504-a4dd-11e6-9b63-371e3e775581.png)

**Comment by elvesater** [comment]
Fixed. If no keywords we hide the panel altogether.
