### ISSUE TITLE
Versioning of file pages does not cover keywords

### ISSUE THREAD

**Issue by nvnikolov** [datagraft/datagraft-portal#53]
Keywords are not reflected in versions of the filestores (you always get the latest keywords when browsing older versions of the filestore)

**Comment by sdalgard** [comment]
Implemented double storage of keywords.
  Act_as_taggable for searching and statistics
  Metadata for interface to UI and assuring correct versioning.

From UI keywords are always written to act_as_taggable and metadata (equal content)
To UI keywords are read from metadata.
This assures rollback of older keywords from metadata.

IMPORTANT:
Views must use meta_keyword_list to make correct behaviour.

**Comment by sdalgard** [comment]
Consistent implementaion made for Filestore and SPARQL_endpoint
