### ISSUE TITLE
Show old asset version not as intended(?)

### ISSUE THREAD

**Issue by sdalgard** [datagraft/datagraft-portal#61]
A list of old versions for a filestore is possible by clicking the versions button in the show view.
When an old version is selected by clicking show, the old version is showed.

When showing the old version, the copy button is copying the latest version.
When showing the old version, edit is editing the latest version.

Is this the wanted behaviour?

**Comment by nvnikolov** [comment]
Copying old versions should be possible; Editing should be as-is - edit the current version

**Comment by sdalgard** [comment]
Fixed :-)

**Comment by sdalgard** [comment]
Fixed for ting and filestore
