### ISSUE TITLE
Landingpage create wordcloud

### ISSUE THREAD

**Issue by sdalgard** [datagraft/datagraft-portal#75]
Who uses Datagraft?
 - Buisiness
 - IT
 - Data Workers

**Comment by nvnikolov** [comment]
Courtesy of Dina - please remove the unneeded ones :smiley_cat: :
Data Scientist
Business Analyst
Analyst
Data Analyst
Statistician
Senior Analyst
Senior Data Scientist
Chief Scientist
Research Scientist
Analytics Manager
Business Intelligence Consultant
Senior Business Analyst
Analytics Consultant
Data Architect
Research Analyst
Scientist
Web Analyst
Chief Data Scientist
Director of Analytics
Director, Analytics
Lead Analyst
Principal Data Scientist
Quantitative Analyst
Principal Scientist
SAS Programmer
Senior Web Analyst
Database Administrator
Director of Research
Director, Web Analytics
Lead Data Scientist
Lead Scientist
Manager Analytics
Manager, Analytics
Market Research Analyst
Senior Credit Risk Analyst
Senior Manager, Business Analytics
Senior Marketing Analyst
Senior Research Scientist
Sr. Statistician
Statistical Consultant
Vice President - Analytics
Web Analytics Manager
Actuary
Advanced Analytics Consultant
Analytic Scientist
Analytics Scientist
Analytics Specialist
Associate Business Analyst
Biostatistician
Business Analysis Manager
Business Analytics Director
Business Intelligence Analyst
Business Intelligence Specialist
Chief Analytics Officer
Data Analytics Consultant
Data Anayltics Professional
Data Engineer
Data Manager
Data Miner
Director of Advanced Analytics
Director, Advanced Analytics
Director, Data Science
Enterprise Information Architect
IT Business Analyst
Information Management Specialist
Lead Statistician
Machine Learning Engineer
Manager analytics
Manager of Analytics
Manager, Business Analytics
Mathematician
Planning Analyst
Principal Research Scientist
Quant
R&D Director
Reporting Analyst
Research Director
Research Engineer
Research Manager
Research and Development Manager
Risk Analytics Manager
Risk Consultant
Risk Manager
Risk Officer
SAP Solution Architect
SAS Consultant
SAS Data Analyst
Senior Analytics Consultant
Senior Bioinformatics Scientist
Senior Business Intelligence Consultant
Senior Business Intelligence Developer
Senior Data Analyst
Senior Market Analyst
Senior Research Analyst
Senior Statistician
Sr Quantitative Analyst
Sr. Data Scientist
Sr. Risk Analyst
Statistical Programmer
Statistical Programmer (SAS)
System Analyst
Systems Analyst
Technical Business Analyst
VP of Analytics
Vice President, Analytics

**Comment by sdalgard** [comment]
Implementd in branch feature/Landingpage
