### ISSUE TITLE
Wizard and Things are not deleted when user is deleted

### ISSUE THREAD

**Issue by sdalgard** [datagraft/datagraft-portal#85]
This results in zoombie wizards.
We have to check if this is the case for all items with "has_many" relation

Procedure:
1. Create a new user
2. Create a file asset
3. Delete the used
4. Check if filestore thing remains (how?)

**Comment by jcserracampos** [comment]
Hello,
I came from label `help wanted`
If you want do destroy nested entries you have to use:
`has_many :filestores, dependent: :destroy`

I can create a PR if you want.

**Comment by sdalgard** [comment]
@jcserracampos 
Thanks for help :-)
I need to analyse if we can automatically delete, or if some business logic is needed.

**Comment by jcserracampos** [comment]
@sdalgard 
If your nested models have validations for destroy action, it's safe to use dependent.
E.g.:
You can't destroy Users with active orders, so you need to valide inside Order.

**Comment by sdalgard** [comment]
I have now tested deletion of filestore
Filestores belonging to a user is not deleted when the user is deleted (se comment above)

We have to decide on public filestores (accesible for other users)
Is it ok to delete these when deleting user?
 - If they shall remain while the user is deleted, they will point to 'nil'
 - Then we need to make the code more robust (see attached screenshot)

![image](https://cloud.githubusercontent.com/assets/2270169/23263200/c76f2836-f9dd-11e6-9d82-84b396e28a80.png)

**Comment by sdalgard** [comment]
Implemented in branch "feature/userasset_deletion"
Ready for integration
