### ISSUE TITLE
How shall missing ID be handled

### ISSUE THREAD

**Issue by sdalgard** [datagraft/datagraft-portal#86]
When a URL for a missing ID is requested, an exception is rised "ActiveRecord::RecordNotFound"
How should this be guided into a flash error message?

The code in question is located in app/controllers/concerns/thing_concern.rb:28:in `set_thing' called from things_controller before action.
  before_action :set_thing, only: [
    :show, :edit, :update, :destroy, :star, :unstar, :fork, :versions,
    :show_metadata, :edit_metadata, :delete_metadata,
    :show_configuration, :edit_configuration, :delete_configuration, :update_partial
    ]

![image](https://cloud.githubusercontent.com/assets/2270169/23700952/07bf2a50-03f5-11e7-8593-91d0ed356d49.png)

**Comment by nvnikolov** [comment]
Isn't that is how it is supposed to be? When you request a resource in the browser that doesn't exist you should in fact get a 404 error.
